### PR TITLE
New parser, updated quantizer

### PR DESCRIPTION
**Pull request by nick5429**
Great project!

I wanted to be able to get the imdb "rating" field (score from 1-10 of how "good" the movie is), and created a new parser which supports that.

I created a new parser for "myapifilms", which gets its data from IMDB.  The existing "mymovieapi" site unfortunately seems to be down/gone.

I also updated the quantizer with a few new fields: letter (first letter of the movie name) and an additional 'ratings' bucket which rounds the 'rating' to the nearest 0.5

### CODE REVIEW

**Comment by hufman** [comment]
That looks great! Can you add unit tests for your quantizer, and maybe some unit tests for the myapifilms plugin?
Can you mention, in the myapifilms docs, that the rating could be decimal? Also I think you left a mymovieapi copy-paste error in there :)
Can you get Artists working in myapifilms? Then it'll be perfect!

**Comment by nick5429** [comment]
- Added fix/workaround in the quantizer for a bug with 'year' output when 'year' is an int instead of a string, and corresponding test showing that it's broken as-is
- MyApiFilms 'actors' come back as an array of json objects with [{"actorName":"Actor's Name", <other info on this actor>}], which is different from the expected format elsewhere in the program. Python is not my forte, so I just don't set the 'actors' field in myapifilms, rather than trying to manipulate/massage the objects into the expected format as a list of names
- Added tests for rating and letter quantizer
- Added tests for myapifilms parser

**Comment by hufman** [comment]
Thanks for all the tests! :D

Hooray, you get to learn a really neat feature in Python, called List Comprehensions! It's just pretty syntax around a map function. With your array of objects, you could do something like this:

``` py
apiResult = [ {"actorName": "Actor's Name"}, {"actorName": "Other Actor"} ]
names = [ obj["actorName"] for obj in apiResult ]
```

Can I ask you to merge some of the commits so that each new feature is a single cohesive commit? And then you can push -f back up to the branch. Thanks!

**Comment by nick5429** [comment]
Rebased to consolidate commits

**Comment by nick5429** [comment]
Friendly reminder to merge this in :)

**Comment by hufman** [comment]
Sorry! I've been distracted with other projects and haven't had time to focus on this one!

**Pull request merged**
